app.db.url=jdbc:postgresql://localhost:5432/pidev_db
app.db.user=postgres
app.db.password=admin

app.oauth.google.clientId=
app.oauth.google.clientSecret=
app.oauth.google.callbackPort=8765

app.ai.useMock=true
app.ai.openai.apiKey=
app.ai.openai.model=gpt-4o-mini

app.mail.enabled=false
app.mail.from=
app.mail.smtp.host=smtp.gmail.com
app.mail.smtp.port=587
app.mail.smtp.username=
app.mail.smtp.password=
app.mail.smtp.starttls=true
app.mail.smtp.ssl=false
